image:
  repository: "${ZARF_REGISTRY}/ironbank/atlassian/jira-data-center/jira-node"
imagePullSecrets:
  - name: private-registry
ingress:
  nginx: false
istio:
  enabled: true
  gateways:
    - istio-system/public
